export const markup = `
<canvas id="arena" aria-label="Luma Coil game arena"></canvas>
<div id="menu" class="menu-shell site-menu">
 <header class="topbar"><a class="wordmark" href="/" aria-label="Luma Coil home"><span class="brand-icon">ϟ</span> luma<span>coil</span><span class="beta">VOL. 02</span></a><div class="top-actions"><span class="live-status"><i class="online"></i> YOUR OWN LITTLE COSMOS</span><button class="icon-btn" id="settings" aria-label="Settings">⚙</button></div></header>
 <main class="menu-main"><section class="intro"><div class="eyebrow"><span></span> YOU, A SPARK & A LITTLE CHAOS</div><h1>Small beginnings.<br><em>Infinite possibilities.</em></h1><p class="lede">Find your flow. Chase the glow.<br>Outgrow a world of clever coils.</p>
 <section class="play-card"><div class="card-top"><span>MAKE YOUR ENTRANCE</span><span class="guest-tag">NO SIGN-UP. JUST PLAY.</span></div><label class="field-label" for="name">What should we call you?</label><div class="name-field"><span class="input-star">✳</span><input id="name" maxlength="20" placeholder="Wanderer" autocomplete="nickname" spellcheck="false"/><span class="field-hint">OPTIONAL</span></div>
 <div class="skin-label"><span>Pick your energy</span><span id="skin-name">Ion</span></div><div class="skins" id="skins" role="group" aria-label="Snake skin"></div>
 <div class="mode-tabs" role="group" aria-label="Game mode"><button id="mode-quick" class="selected" aria-pressed="true">Quick Play</button><button id="mode-custom" aria-pressed="false">Custom Game</button></div>
 <div id="custom-options" hidden><div class="selection-label">AI difficulty</div><div id="difficulties" class="difficulty-grid" role="group" aria-label="AI difficulty"></div><p id="difficulty-note" class="difficulty-note"></p><div class="count-row"><span>AI players</span><div id="counts" role="group" aria-label="AI players"></div></div></div>
 <div class="game-summary"><span>Difficulty <strong id="chosen-difficulty">Normal</strong></span><span>AI players <strong id="chosen-count">20</strong></span></div>
 <button id="quick" class="primary"><span>Play</span><span class="button-end">FIND YOUR FLOW <b>↗</b></span></button>
 <div id="menu-error" class="error" role="alert" hidden></div><div class="card-foot"><span class="little-dot"></span> SINGLE PLAYER. ENDLESS POSSIBILITIES.</div></section>
 <button id="how" class="how-button"><span class="help-circle">?</span> First time around? <strong>How to play</strong> <span>↗</span></button></section>
 <aside class="hero-note"><span class="tiny-orbit">✳</span><div>GOOD THINGS<br>COME AROUND.</div><span class="hero-index">001 / ION</span><div class="session-card"><span class="eyebrow">THIS SESSION</span><div id="session-stats"></div></div></aside></main>
 <footer class="menu-footer"><span>STAY CURIOUS. KEEP GROWING.</span><div><span><i class="keycap">↖</i> MOVE</span><span><i class="keycap">SPACE</i> BOOST</span><span><i class="keycap">ESC</i> PAUSE</span></div><span>MADE FOR A LITTLE FRIENDLY CHAOS.</span></footer>
</div>
<section id="hud" hidden><div class="hud-left"><span class="hud-brand">ϟ luma<span>coil</span></span><div class="room-pill"><i class="little-dot"></i><span id="room-label">NORMAL · 20 AI</span></div><div class="score-box"><span class="hud-caption">YOUR MASS</span><strong id="score">32</strong><span class="rank-line">RANK <b id="rank">1</b><span> / </span><b id="players">21</b> SNAKES</span><span id="population" class="rank-line">YOU + 20 AI</span></div></div><div class="leaderboard"><div class="board-title">THE BRIGHTEST <span>TOP 10</span></div><ol id="leaders"></ol><div class="board-footer"><span id="time">0:00</span><button id="sound-toggle" aria-label="Toggle sound">♪</button><button id="pause" aria-label="Pause game">Ⅱ</button><button id="leave">Menu ↗</button></div></div><div class="boost-hint"><span id="boost-label">COLLECT SPARKS TO UNLOCK BOOST</span><div class="boost-track"><i id="boost-fill"></i></div></div><button id="touch-boost">BOOST ↑</button></section>
<div id="toast" role="status" hidden></div>
<dialog id="modal"><button id="modal-close" aria-label="Close dialog">×</button><div id="modal-content"></div></dialog>
<dialog id="pause-dialog"><span class="eyebrow">TAKE A LITTLE BREATHER</span><h2>The glow can wait.</h2><p>Your whole arena is paused.</p><button class="primary" id="resume">Keep flowing <b>↗</b></button><button class="text-btn" id="pause-menu">Main menu</button></dialog>
<dialog id="death"><span class="eyebrow">EVERY END IS A BEGINNING</span><div class="death-symbol">✳</div><h2>A beautiful little run.</h2><p id="death-reason"></p><div class="death-stats"><div><span>FINAL SCORE</span><strong id="death-score"></strong></div><div><span>FINAL RANK</span><strong id="death-rank"></strong></div><div><span>TIME SURVIVED</span><strong id="death-time"></strong></div><div><span>FOOD EATEN</span><strong id="death-food"></strong></div><div><span>PEAK MASS</span><strong id="death-peak"></strong></div><div><span>DIFFICULTY</span><strong id="death-difficulty"></strong></div></div><button class="primary" id="respawn">Respawn <b>↗</b></button><button class="text-btn" id="back-menu">Main menu</button></dialog>`;
